### PR TITLE
Merge with graspi

### PR DESCRIPTION
**Pull request by wd15**
Integrate GraSPI into PyMKS. 

This is largely a test PR to see the builds working correctly and view sample documentation.

Further list of task, #529

## Issues

 - [x] Nix build works
 - [x] pip build won't work as boost can't be added. Boost needs to be optional for pip and turn off graph descriptors in that case
 - [x] will the documentation build without Boost
 - [x] still need to make a conda build

### CODE REVIEW

**Review by owodo — APPROVED** [review]
Checked, all files included.

**Review by auag92 — APPROVED** [review]

**Comment by wd15** [comment]
I'm having second thoughts about merging Graspi. I think that we should focus on making Graspi a separate Python package.

**Comment by owodo** [comment]
What made you rethink this idea? Any particular reason?

**Comment by wd15** [comment]
> > What made you rethink this idea? Any particular reason?
> 

Also, easier for you to keep developing without having to learn all the PyMKS infrastructure.

**Comment by owodo** [comment]
Sounds good, please open the issue on the repository. Then in the wrapper, we can aggregate the set of descriptors. I think it would be a good (and a faster) way to transition between Graspi (that is focused on organic solar cells) and a new package that would be more generic.

**Comment by wd15** [comment]
Closed in favor of #553

**Pull request closed without merging**
