### PR TITLE
docs(notebooks): update stress.ipynb for fmks

### PR DESCRIPTION
**Pull request by beyucel**
Stress notebook is updated with `fmks` functions.
-  Homogenization workflow is performed with `sklearn` pipelines and `fmks` functions.
- Old PyMKS tools for visualization are removed
- Descriptions(Markup cells) are updated with `fmks` descriptions.
- Issue of nondeterministic results are investigated ( This solves the #396 )
- Multiple pipelines were created to show that the user can control every step of the homogenization workflow with `fmks` version of the `PyMKS`.

This PR also solves #422. (#421 still needs to be done, this notebook uses the`make_elastic_stress_random`).

### CODE REVIEW

**Comment by beyucel** [comment]
@wd15  and @auag92, please review this PR. I updated some parts of the markup cells with fmks discussion. Most of the discussion is same as the previous version of the stress notebook. If you can check the updates and notebook in general, I would appreciate that.

**Comment by beyucel** [comment]
Solved the issue with  cell output mismatch

**Comment by wd15** [comment]
Can I rebase this for you just for the commit messages?

**Comment by beyucel** [comment]
Sure! Thanks for doing that.

**Comment by wd15** [comment]
Let's try and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) now. I'll show you when I rebase. I'm using it in PyMKS and I have the commit messages linted by the CI. It makes for a much more readable and searchable history in the long run.

**Comment by beyucel** [comment]
Sure, I saw the #416. I took a look at the documentation, I will try to use it but if you can show how we can use it that would be great.

**Comment by wd15** [comment]
This is really nice now with the pipelines. It's a massive improvement. A few things

 - After cell 9, there is a graph and the text says that 93% of the variance is captured with the first 5 components, but the graph is only at about 80%. I guess this has changed by a lot since the last version of PyMKS which is kind of weird. What do you think is going on? Has the PCA changed?

 - Text after Cell 5 is still referring to `MKSHomogenizationModel`

 - Shall we move all imports to the first cell? I think it's easier to see what the notebook uses with a quick glance.

All the tests pass for me in a Nix environment. 

I won't rebase yet until we get the above issues straight.

**Comment by beyucel** [comment]
> This is really nice now with the pipelines. It's a massive improvement. A few things
> 
Thanks, @wd15 for the review.
>  - After cell 9, there is a graph and the text says that 93% of the variance is captured with the first 5 components, but the graph is only at about 80%. I guess this has changed by a lot since the last version of PyMKS which is kind of weird. What do you think is going on? Has the PCA changed?
> 
I corrected the issue. The issue was the type of two-point correlations used for both notebooks were different (old version was using [(0,0),(1,1)] and this version was using   [(0,1),(1,1)] ). Also, when I was getting the values for explained variance I was using ` pca.explained_varience_` instead of  `pca.explained_varience_ratio`. I corrected that as well. I think it looks better now.

>  - Text after Cell 5 is still referring to `MKSHomogenizationModel`
> 
Corrected!
>  - Shall we move all imports to the first cell? I think it's easier to see what the notebook uses with a quick glance.
> 
I moved all imports to the first cell.
Again thanks for your review, Daniel!
> All the tests pass for me in a Nix environment. 
> 
> I won't rebase yet until we get the above issues straight.

**Comment by wd15** [comment]
I'm going to rebase this now

**Pull request merged**
