### PR TITLE
Pair correlations

### PR DESCRIPTION
**Pull request by SvenPVoigt**
Pair Correlations can be calculated in many ways. In this pull request, I am calculating pair correlations from 2point statistics- in the new function `paircorr_from_twopoint`. One caveat of using two point statistics is that at large r values, probability values become very small and closely spaced. Therefore, the function provides a `cutoff_r` and an `interpolate_n` parameter for dealing with probabilities at large r values.

Additionally, I provide a `dist_from_center` function, which could be used in other functions as well because it is so generic.

I put both functions in `pair_correlations.py`, but I am open to adding `dist_from_center` in `func.py` and `paircorr_from_twopoint` in `correlations.py`. If I change the location of the functions, is there a git tool (maybe the squash and merge option) for cleaning up commits so that only the changes to final (not intermediate) files are represented?

Also, if there is any area for increasing the usage of dask, please let me know. I will try to identify some additional spots as well. Right now, I am simply validating that dask and numpy arrays can be passed as input to my functions.

### CODE REVIEW

**Comment by wd15** [comment]
@SvenPVoigt nice job. I'll hopefully review this in the next few days.

**Comment by wd15** [comment]
I'm a little confused. I think that `paircorr_from_twopoint` should return a tuple with the probabilities in the first item and the radii in the second item. I don't think it's good to store data with different units in the same array. Also, the probabilities should be shaped `(n_samples, n_interpolate)` to fit in with how the first axis is the sample axis as in the rest of PyMKS. What do you think?

**Comment by wd15** [comment]
New `dist_from_center` code?

```
center = lambda x: np.reshape(
    np.array(x) // 2,
    (len(x),) + (1,) * len(x)
)
    
dist_mesh = sequence(
    fmap(lambda x: np.linspace(0, x - 1, x)),
    lambda x: np.array(np.meshgrid(*x, indexing='ij')),
    lambda x: x - center(x.shape[1:]),
    lambda x: np.linalg.norm(x, axis=0)
)
```

**Comment by wd15** [comment]
@SvenPVoigt I've [made a PR into your branch](https://github.com/SvenPVoigt/pymks/pull/4). You probably should merge upstream's master and rebase and then I'll redo the PR. Anyway I've made things more functional. Also,

 - added `paircorr_from_twopoint` to the API docs
 - make `make_da` keep its docstring
 - Made the docstring better

You might want to check that you're happy with the API docs.

**Comment by wd15** [comment]
@auag92, @beyucel : can you both review this now. It's ready. Also, @SvenPVoigt can you also give your seal of approval in the comments. Thanks

**Comment by wd15** [comment]
@auag92 @beyucel : I added @SvenPVoigt new function to the API so please check that it reads well, https://pymks--524.org.readthedocs.build/en/524/API.html#pymks.paircorr_from_twopoint

**Review by auag92 — APPROVED** [review]

**Review by beyucel — APPROVED** [review]

**Pull request merged**
