### PR TITLE
Declared type for np.arange, this is required for numpy 1.10

### PR DESCRIPTION
**Pull request by bodagetta**

### CODE REVIEW

**Comment by ahmetcecen** [comment]
I second this. Although you should send the request again for the develop branch of pymks.

**Comment by bodagetta** [comment]
It's your code after all :) Thanks for all the help figuring this out. I submitted a pull request on the develop branch as well. I noticed you closed this without merging it. Does that mean it was rejected and I should have only submitted to the development branch for later merge into master? 

I'm not entirely familiar with the workflow and want to make sure I'm doing things the preferred way.

**Comment by ahmetcecen** [comment]
Yes, we tend to only merge to master from develop. So anyone contributing
sends a pull request to develop, after a number of changes and stability
checks we merge develop to master.

**Comment by bodagetta** [comment]
That makes sense. I'll be sure to submit only to develop in the future.

**Pull request closed without merging**
