### PR TITLE
Add conda-forge to Circle CI and include conda-forge installation instructions

### PR DESCRIPTION
**Pull request by wd15**

### CODE REVIEW

**Comment by beyucel** [comment]
I guess `python setup.py install` was the issue with the conda installation this solves #520

**Comment by beyucel** [comment]
After checking with Linux and Windows, Linux works fine but windows installation still gives RandomizedPCA error.

**Comment by wd15** [comment]
> After checking with Linux and Windows, Linux works fine but windows installation still gives RandomizedPCA error.

You're still getting the same error from #520. I'll answer in that issue.

**Comment by wd15** [comment]
@beyucel @auag92 @SvenPVoigt feel free to review this now

**Comment by beyucel** [comment]
> > After checking with Linux and Windows, Linux works fine but windows installation still gives RandomizedPCA error.
> 
> You're still getting the same error from #520. I'll answer in that issue.

I just checked it again. It was a local problem. There is no problem with the Windows installation. I checked all notebooks (with conda-Windows).

**Review by beyucel — APPROVED** [review]

**Comment by SvenPVoigt** [comment]
Looks like the grid search parameter (in the fibers notebook) has some random variability to it. Is there any guarantee the check will pass with the new assertion? Otherwise, maybe we should leave out the assertion.

**Comment by wd15** [comment]
> Looks like the grid search parameter (in the fibers notebook) has some random variability to it.

We don't want any variability ideally, but I haven't figured out how to seed it.

> Is there any guarantee the check will pass with the new assertion `1<param<3`?

Those are the only choices we're trying (from 1 to 3)! The poly degree doesn't have much influence.

> In general are there any guidelines on whether to check random variables or leave them out of tests?

We shouldn't have randomness that isn't seeded as part of the tests. Just have to live with it for now unless we can figure out how to fix it.

**Comment by SvenPVoigt** [comment]
Alright. Thanks for the answer!

> Those are the only choices we're trying (from 1 to 3)! The poly degree doesn't have much influence.

Great, the test is guaranteed to pass then. I will approve.

**Review by SvenPVoigt — APPROVED** [review]

**Review by auag92 — APPROVED** [review]

**Comment by wd15** [comment]
> Alright. Thanks for the answer!
> 
> > Those are the only choices we're trying (from 1 to 3)! The poly degree doesn't have much influence.
> 
> Great, the test is guaranteed to pass then. I will approve.

If you can figure out a way to make the example deterministic then I buy you a beer.

**Pull request merged**
