### PR TITLE
Fixed Nonperiodic Correlations and Implemented Masked Correlations

### PR DESCRIPTION
**Pull request by SvenPVoigt**

### CODE REVIEW

**Comment by wd15** [comment]
I've made a [PR](https://github.com/SvenPVoigt/pymks/pull/1) into your master branch to clean this up. A few things.

 - Tests were failing in [`auto_correlation`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/correlations.py#L71) and [`cross_correlation`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/correlations.py#L20). As they were assuming normalization. I fixed those, but changed the description of the function to say that these are both now non-normalized.

 - I cleaned up up the notebook and used [`plot_microstructures`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/plot.py#L29) to do the plotting. I changed the checks to be assertions rather than outputs.

 - I moved the notebook to `pymks/fmks/tests` as it's really a test notebook rather than an example. The `notebooks` directory is really for examples so perhaps we should rename it to `examples` rather than `notebooks`. Something to do separate to this PR. It's actually a good idea to have notebooks in the module tests as I think it's easy to narrate the testing that way. 

 - I fixed style issues so that the linters passed. If you follow lines 22-25 [here](https://github.com/materialsinnovation/pymks/blob/master/.travis.yml#L22) then you can fix things locally before committing. Run Black first as it automatically fixes issues (without the `--check` flag).

 - Likewise checking that the tests pass is a good idea before committing or PR

Some things to consider:

 - Obviously, as things are written, there is no masking available for the [`TwoPointCorrelation`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/correlations.py#L234) transformer. Do you want that? We could either have a single mask that is the shape of the domain or a different mask for each sample in which case the mask needs to be chunked the same as the microstructure array. If we only have a single mask for all the samples then it doesn't actually need to be a dask array. In that case there is no need to call `compute` just cast it to a numpy array so then it can be any sequence type. We can address this in another PR.

 - In the long run, it might be better if we just use [`map_blocks`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/func.py#L91) in [`correlation_multiple`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/correlations.py#L196) and then have all functions above just ordinary numpy functions without any dask at all. Not something for this PR though.

 - Can you add more narrative in the test notebook? For example why we need the tests. What bug it was fixing. It's much easier when someone comes to look at it in a year or two to figure out what it does.

 - Do you want to add an example style notebook in another PR or this one where we work on adding this to the [`TwoPointCorrelation`](https://github.com/materialsinnovation/pymks/blob/master/pymks/fmks/correlations.py#L234)? Your choice. Probably easier to merge this and start fresh.

**Comment by SvenPVoigt** [comment]
Thanks for looking this over.

* After I started the pull request, I realized I tried adding changes to master. Perhaps I should submit a PR to a feature branch instead?

* I wanted a theoretical notebook first to validate the calculations- I will add more descriptions in the notebook to discuss what is happening. The notebook includes hard-coded microstructures and hand computed answers.

* As far as features go we need to discuss the following
    * What will the mask look like? 
        * For example, you stated that we may want a different mask for each sample. This is the case in the example I hope to demonstrate, and I may need to put some more thought into how to pass the chunked array to the function.
        * Will the mask be boolean or floating point? I only have boolean examples, and we may want to change terminology to weights instead of masks if we go with floating point values. The tests notebook also needs a weight example now that I am mentioning it.
    * Which functions or classes will accept the mask? I still don't fully understand the import structure and what functions/classes are meant to be the most public/user-facing. Also, we may want to change the mask to the last argument, since there is some some unraveling of lists as arguments. ** unravels a list in order and would assign some value to the mask argument since I placed it before the periodic_boundary argument.

Also, what is the changes requested feature you used above?

**Comment by wd15** [comment]
> Thanks for looking this over.
> 
> * After I started the pull request, I realized I tried adding changes to master. Perhaps I should submit a PR to a feature branch instead?

Yeah, in general that's a little better just for bookkeeping on your own fork, but doesn't matter as far as the main repo is concerned.

> * I wanted a theoretical notebook first to validate the calculations- I will add more descriptions in the notebook to discuss what is happening. The notebook includes hard-coded microstructures and hand computed answers.
>

Makes sense. I think we're ready to merge this after a little more description in the notebook.

> * As far as features go we need to discuss the following
>       
>   * What will the mask look like?
>         
>     * For example, you stated that we may want a different mask for each sample. This is the case in the example I hope to demonstrate, and I may need to put some more thought into how to pass the chunked array to the function.

That's what I guessed. What you have works right now so let's try and merge this. Let's open up another PR to extend it to multiple samples. I can help with that if you have an initial attempt.

> * Will the mask be boolean or floating point? I only have boolean examples, and we may want to change terminology to weights instead of masks if we go with floating point values. The tests notebook also needs a weight example now that I am mentioning it.

If you code it for weights then bools will also work without doing anything extra.

>   * Which functions or classes will accept the mask? I still don't fully understand the import structure and what functions/classes are meant to be the most public/user-facing. Also, we may want to change the mask to the last argument, since there is some some unraveling of lists as arguments. ** unravels a list in order and would assign some value to the mask argument since I placed it before the periodic_boundary argument.

Perhaps we can talk through this on Thursday, but everything can be public facing. I've only added those functions / classes that we use in the notebooks to the public documented API thus far, but we can add more.

> Also, what is the changes requested feature you used above?

PR reviewers can [formally request changes](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews) as part of the PR after they've been assigned.

**Comment by wd15** [comment]
Tests are failing as [we don't have 100% coverage now](https://travis-ci.org/github/materialsinnovation/pymks/jobs/721142853#L7684). I can take care of that.

**Comment by wd15** [comment]
I did another [PR](https://github.com/SvenPVoigt/pymks/pull/2) to add a doctest for test coverage purposes.

**Comment by wd15** [comment]
> 
>   * Ran py.test, still getting a fail in notebooks/stress.ipynb and couldn't figure out how to fix. There is an issue in the pipe, I believe?

Ok, I'll try and debug.

>   * Accidentally added and committed mydask.png. How do I reset this file only? Do I checkout the file from materialsinnovation/pymks?



The easiest way is to redo the commit. Firstly copy the file that you want to a temporary name

    $ cp pymks/fmks/correlations.py pymks/fmks/correlations.py.bkup

and then paste the commit message so you don't lose it

    $ git log -1 > commit.txt

and then roll back to previous commit

    $ git checkout c18fcd9 

and make a new branch
 
    $ git checkout -b branch

Now move the file so that it can be committed

    $ mv pymks/fmks/correlations.py.bkup pymks/fmks/correlations.py

and now add and commit the file to make a new commit using the message in `commit.txt`. Now force push the branch to github

    $ git push -f origin branch:master

This will update the pull request with the new commit and remove the broken commit. Remove the old local master

    $ git branch -D master

and then

    $ git checkout -b master

and then

    $ git branch -D branch

In general I just keep my local master up to date with the upstream master at materialsinnovation and don't use it for development.

**Comment by wd15** [comment]
> * Ran py.test, still getting a fail in notebooks/stress.ipynb and couldn't figure out how to fix. There is an issue in the pipe, I believe?

The stress notebook doesn't appear to be failing. It passes locally for me and it's passing on Travis. The linting is failing on Travis. None of the tests though.

**Comment by wd15** [comment]
Ok, I did another [PR](https://github.com/SvenPVoigt/pymks/pull/3) into your fork. I'll redo it once you've cleanup to remove mydask.png.

**Comment by wd15** [comment]
So, to get this PR finished. Follow my instructions above and then I'll redo the PR into your fork and then I think we'll be good to merge at that point.

**Comment by SvenPVoigt** [comment]
> The easiest way is to redo the commit.

Thank you for the help! The commit is redone.

> In general I just keep my local master up to date with the upstream master at materialsinnovation and don't use it for development.

This is a good idea. In addition to that master branch, would I then have a local branch called something like "fork", which has an upstream branch at my personal github svenpvoigt?

> The linting is failing on Travis.

Not sure what the linting is. To replicate the issues I can run

```
git clone https://github.com/materialsinnovation/pymks.git
cd pymks
conda env create -f environment.yml
source activate pymks
py.test
```

**Comment by SvenPVoigt** [comment]
> So, to get this PR finished. Follow my instructions above and then I'll redo the PR into your fork and then I think we'll be good to merge at that point.

Sounds good.

**Comment by SvenPVoigt** [comment]
I messed up. I merged Dan's PR into my fork after redoing the commit. This readded the dask.png file. Will redo the commit again and then try and see if I can selectively added the lint fixes.

**Comment by wd15** [comment]
> I messed up. I merged Dan's PR into my fork after redoing the commit. This readded the dask.png file. Will redo the commit again and then try and see if I can selectively added the lint fixes.

I'm happy to fix it if you'd like. Just let me know.

**Comment by wd15** [comment]
We can also fix this together if you want via a video chat

**Review by wd15 — APPROVED** [review]

**Review by auag92 — APPROVED** [review]
Good job with the PR.

**Review by beyucel — APPROVED** [review]
@SvenPVoigt  Awesome job! Great tests and additions. I am approving this PR, I have 2 comments for discussion:
1- As we moved the normalization out of auto_correlation and crosscorrelation functions, TwoPointCorrelation (+ .transform()) is the main way of calling the two-point statistics function. Do we need to consider test cases for that function instead of the `two_point_stats` function? Technically, It is  the same thing because `TwoPointCorrelation` calls `two_point_stats` but just asking.
2- As far as I remember, we don't use ".compute()" in the main code and we are not saving anything to memory. I know that it (line 206 correlations.py) only gets the max and min values for the mask but do you think if this negatively affects the parallel computation?

@wd15  what do you think?

**Pull request merged**
