### PR TITLE
feat: generator function for multiphase microstructures 

### PR DESCRIPTION
**Pull request by auag92**

### CODE REVIEW

**Comment by beyucel** [comment]
I guess this is failing because some of the functions need "docstrings". Also, I guess we talked yesterday and I forgot, can you share the code for generating 3D microstructures

**Comment by auag92** [comment]
> I guess this is failing because some of the functions need "docstrings". Also, I guess we talked yesterday and I forgot, can you share the code for generating 3D microstructures

I had wrongly suggested yesterday that this multiphase code has 3d capability. The old pymks logic that I ported over can only generate 2D microstructures. 

 I will share an ad-hoc 3 multiphase generator to you now... but let's add that to pymks as a separate pull request later.

**Comment by auag92** [comment]
> I guess this is failing because some of the functions need "docstrings". Also, I guess we talked yesterday and I forgot, can you share the code for generating 3D microstructures

You can use the multiphase.py code in this branch to generate 3D microstructures.
You can call the generate function as follows:

x_data = _npgenerate(n_phases=5, 
                                      shape=(5, 101, 101, 101), 
                                      grain_size=(25, 25, 25), volume_fraction=None, seed=10)

**Comment by wd15** [comment]
Opened up a new PR for this since I can't change this from being a draft, #458

**Pull request closed without merging**
