### PR TITLE
Issue325 default fft

### PR DESCRIPTION
**Pull request by wd15**
Use Numpy's fft by default unless the `PYMKS_USE_FFTW` environment variable is set or `use-fftw` is set in setup.cfg on install. PyFFTW is quite fragile so it is best to explicitly use PyFFTW rather than use it by default if installed.

Other changes include modifying a test in  `pymks/tests/test_stats.py`, which seemed to not be deterministic. It assumed that the run time would be less for larger number of threads, which is heavily dependent on resources on the current workstation. Under some circumstances the run time could be greater with more threads.

Address #325

### CODE REVIEW

**Comment by davidbrough1** [comment]
@wd15 when running the tests with Python 2.7.11 I get the following error with the following traceback.

    python -c "import pymks; pymks.test()"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "pymks/__init__.py", line 3, in <module>
        from .bases.primitive import PrimitiveBasis
      File "pymks/bases/__init__.py", line 1, in <module>
        from .primitive import PrimitiveBasis
      File "pymks/bases/primitive.py", line 1, in <module>
        from .real_ffts import _RealFFTBasis
      File "pymks/bases/real_ffts.py", line 2, in <module>
        from .fftmodule import rfftn, irfftn
      File "pymks/bases/fftmodule.py", line 33, in <module>
        import configparser
     ImportError: No module named configparser

Also it doesn't look like `ConfigParser` from Python 2.7.11 has a `read_string` method.

**Comment by wd15** [comment]
All the Python 2 tests passed!

https://travis-ci.org/materialsinnovation/pymks/jobs/171225565

Something must be weird with the tests. Let me figure this out.

**Comment by wd15** [comment]
@davidbrough1, I'm not sure why all the Py2 tests pass on Travis CI. My guess is that `configparser` is a dependency of one of the other packages that PyMKS depends on so it gets installed anyway. However, I've added it as a explicit dependency now so everything should work. Your tests should all pass if you do

    $ pip install configparser

in Py2. `configparser` is built into Py3, but it still lets you pip install it, probably to be compatible with Py2, which is good. The `read_string` thing doesn't appear to be an issue.

I don't think `read_string` is an

**Comment by wd15** [comment]
I also added an explicit install of `configparser` in the travis.yml to be safe.

**Comment by davidbrough1** [comment]
After installing `configparser` I was able to run the tests and they all passed, but after changing

    use-fftw = true

into [this bug](https://github.com/materialsinnovation/pymks/issues/304). It looks like the order of imports needs to be rearranged.

**Comment by wd15** [comment]
@davidbrough1, thanks David, I'll get on that. Also, I think that none of the tests are using pyfftw so I'll fix that as well.

**Comment by wd15** [comment]
@davidbrough1, I made

```
try:
     import pyfftw
except ImportError:
    pass
```

the very first thing that happens in pymks so that pyfftw is always imported before numpy even if it isn't' used.

I also added a RuntimeError for the actual pyfftw import so that I check it's being used on Travis CI. Wait for the next commit before merging.

**Comment by wd15** [comment]
Tests are definitely seeing the `PYMKS_USE_FFTW` flag and using pyfftw for Travis CI.

**Comment by wd15** [comment]
@davidbrough1, I wasn't seeing the same errors as you as I was using the conda-forge channel to install pyfftw. That doesn't have the import order issue, correct?

**Comment by wd15** [comment]
@davidbrough1, all tests pass. Remember to test locally as the Travis CI tests are using conda-forge for pyfftw which won't show the import error bug if it's still broken (which it shouldn't be now).

**Comment by davidbrough1** [comment]
All my local tests passed for commit f584ad7.

**Pull request merged**
