### PR TITLE
build(nix): update to use Nixpkgs version 19.03

### PR DESCRIPTION
**Pull request by wd15**
Address #414, #345 

Update the Nix build to use Nixpkgs version 19.03. This has a version
of Scipy that deals with #345.

 - Simplify build into one file and remove nix/ directory
 - Only use Nixpkgs recipes other than Sfepy
 - All tests pass for me
 - Currently adding Sfepy to Nixpkgs, will update when added or at next official release of Nixpkgs
 - Updates to use Scikit-learn 0.20.2 and also remove some deprecation warnings
 - Nbval needs a small modification which is no longer needed on HEAD of Nixpkgs
 - Update the Conda build so that it is compatible with new code updates
   - Note that Sfepy is at 2019.2 for Nix, but 2018.2 for Conda. Conda won't resolve Sfepy 2019.2 with either Python 3.6 or Python 3.7. It also won't resolve Python 3.7 with Sfepy 2018.2 so using Python 3.6 for the Conda build.
 - Would it make sense to add PyMKS to Nixpkgs?

BTW, I tried installing this 
```
name: pymks
channels:
  - conda-forge
dependencies:
  - python=3.6
  - sfepy=2018.2
```
Only the above works after trying different combos of Python 3.6, 3.7 and Sfepy 2018.2 and 2019.2. I'll file a bug with Sfepy on this.

The commits in this PR are using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)

### CODE REVIEW

**Comment by beyucel** [comment]
Hi Daniel, That is **awesome**!!
I tested the NIX version and works perfectly. I ran the test and I also checked all of the notebooks (the only issue is `fiber` notebook takes too long - I need the update the Grid search, I will do that). There is no problem for NIX.

For `conda`, we (Apaar and I) still need to update `conda-forge ` recipe. I created the environment with `environment.yml` when I ran : 

       $ python -c "import pymks; pymks.test()"
 all tests passed. However, I had an issue that I could not identify for Jupyter notebooks. Can you (@wd15 ) and Apaar (@auag92) check if you have any problems on the notebooks for Conda? It could not even import `pymks` on Notebook. I did not have that issue on the `conda` terminal (I checked the version of the Python and Jupyter. I am using the correct versions but I am still getting the error).

Thank you,

**Comment by wd15** [comment]
> Hi Daniel, That is **awesome**!!

Well, thanks for reviewing!

> I tested the NIX version and works perfectly. I ran the test and I also checked all of the notebooks (the only issue is `fiber` notebook takes too long - I need the update the Grid search, I will do that). There is no problem for NIX.

Right, that's not related to this PR though. It was slow before I made these changes. Maybe create another issue.

> For `conda`, we (Apaar and I) still need to update `conda-forge ` recipe. I created the environment with `environment.yml` when I ran :
> 
> ```
>    $ python -c "import pymks; pymks.test()"
> ```
> 
> all tests passed.

Very good.

> However, I had an issue that I could not identify for Jupyter notebooks. Can you (@wd15 ) and Apaar (@auag92) check if you have any problems on the notebooks for Conda? It could not even import `pymks` on Notebook. I did not have that issue on the `conda` terminal (I checked the version of the Python and Jupyter. I am using the correct versions but I am still getting the error).

Did you forget to to run `python setup.py develop` in your new environment? Otherwise pymks won't be on the Python path.

**Comment by wd15** [comment]
@auag92, @beyucel can you both give an approval if you're happy with this.

**Comment by wd15** [comment]
Merging this tomorrow if I don't hear anything from either of you.

**Comment by beyucel** [comment]
Hello Daniel, 
Really sorry for the delay, I don't know why but I was not getting any notification from Github. Everything looks good to me. Once this is merged, I will do separate PR for other notebooks.

Thanks Again,

**Comment by wd15** [comment]
Thanks guys!

**Pull request merged**
