### PR TITLE
Generate Binder instance from the example notebooks

### PR DESCRIPTION
**Pull request by wd15**
To see an example to go to

[Binder](http://mybinder.org/repo/wd15/pymks)

### CODE REVIEW

**Comment by ahmetcecen** [comment]
... ... ...  This is awesome, how have I never heard of this service
before...  This solves a lot of problems that doesn't even exist yet. Let's
see how they scale and if they survive beyond the 700 instance limit they
have right now.

**Comment by ahmetcecen** [comment]
Now I am kinda thinking if it is better to be able to deploy from a
notebook you are already viewing. Maybe we should add the badge with
handles to the rendered version of each notebook.

**Comment by wd15** [comment]
@ahmetcecen, that's a great idea regarding having a badge at the top of each notebook, seems to make sense, but it does have to be maintained, keep a single link in an HTML that's then embedded in each notebook.

Regarding the Dockerfile, I'm planning on adding the documentation so a user could run locally without having to use Binder with just Docker installed. I wouldn't want to rely on Binder for a workshop with 30 participants, obviously.

**Comment by ahmetcecen** [comment]
I managed to get a fully PYMKS capable instance of JupyterHub running on a
personal computer. I think we are planning on making that official in a
monster 3k$ machine that can support about 50 people, both for internal use
and for the workshops, since from experience a lot of people have admin
issues, and a lot of laptops are not advanced enough to support
virtualization technology.

We can use binder for exploring workflows.

The Hub for workshops.

Docker deploy to AWS or Digital Ocean for quick production environment.

Windows Installer and PiP3 for the end user.

**Comment by wd15** [comment]
@ahmetcecen, that's a good idea about Jupyterhub for workshops. They have a docker image, https://github.com/jupyter/jupyterhub#docker. Is that good enough to use for a workshop with the security suggestions they suggest regarding SSL?

Regarding Binder, I agree it is a great exploratory tool for sure. 

Regarding installation of PyMKS. I'm about to make Sfepy conda installable and then it's relatively easy to do the same for PyMKS at that point. I think that will deal with a lot of installation issues.

**Comment by wd15** [comment]
@ahmetcecen, @davidbrough1, I've added the conda builds for sfepy and pymks you should be able to create a new conda environment and then try:

    $ conda config --add channels wd15
    $ conda install pymks
    $ python -c "import pymks; pymks.test()"

We need to create conda builds for mac and windows. Do either of you have an easy way to do that?

The release procedure is now quite complicated involving creating documentation, docker instances and conda builds etc. Maybe we should actually automate some of that.

It might also be nice to create docker and anaconda channels for "materialsinnovation" to match with the github org. All these things are under "wd15" right now.

**Comment by davidbrough1** [comment]
@wd15, I was able to `conda install pymks` on Ubuntu 14.04 LTS and all the tests passed.

I would be in favor of automating the release procedure and creating channels for  "materialsinnovation". 

@ahmetcecen, @fredhohman would you two be willing to help create conda builds for windows and mac?

I would like to do one more release using the old procedure before we merge all of this in.

**Comment by ahmetcecen** [comment]
SfePy is incompatible with 3.5, so it would take quite some time for me to
go through SfePy first, then do conda build skeleton for PyMKS with
dependencies. Otherwise its easy enough, but what would be the point
without the dependencies? Windows Installer already handles all of that for
2.7.

On Wed, Mar 9, 2016 at 11:29 AM, David Brough <notifications@github.com>
wrote:

> @wd15 <https://github.com/wd15>, I was able to conda install pymks on
> Ubuntu 14.04 LTS and all the tests passed.
>
> I would be in favor of automating the release procedure and creating
> channels for "materialsinnovation".
>
> @ahmetcecen <https://github.com/ahmetcecen>, @fredhohman
> <https://github.com/fredhohman> would you two be willing to help create
> conda builds for windows and mac?
>
> I would like to do one more release using the old procedure before we
> merge all of this in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/materialsinnovation/pymks/pull/293#issuecomment-194379059>
> .
>



-- 
Ahmet Cecen
Graduate Student @ Georgia Tech
Computational Science and Engineering

E-mail: ahmetcecen@gatech.edu
Cell: +12675864505
Skype: +16787015869 (ahmetcecen)

**Comment by davidbrough1** [comment]
@ahmetcecen, I agree that porting SfePy to Python 3 would be a huge undertaking. I think we should first create conda builds for Python 2, before worrying about Python 3.

**Comment by wd15** [comment]
@davidbrough1, I think you can merge this pull-request before a release as it doesn't impact any release procedures or code. It's totally independent other than a few changes in the README.

**Comment by davidbrough1** [comment]
@wd15 The current linux conda build for pymks doesn't play nicely with pyfftw. Not sure what the issue is. Is there a way to easily see the difference in conda environments?

**Comment by wd15** [comment]
@davidbrough1, I added an issue for that and will try and address it soon.

**Pull request merged**
