### PR TITLE
Introduce deprecation warnings for all of old pymks

### PR DESCRIPTION
**Pull request by wd15**
- Added deprecation warnings to all functions
 - Added deprecation warnings to all __init__ methods (not all methods)
 - Removed pymks/ from testing only pymks/fmks now
 - Removed requirements.txt as this is now defunct
 - Added Deprecation package to builds

### CODE REVIEW

**Comment by wd15** [comment]
> I am getting Module not found error for the notebooks
> 
> ModuleNotFoundError Traceback (most recent call last)
> in
> 13 from sklearn.linear_model import LinearRegression
> 14
> ---> 15 from pymks import (
> 16 solve_fe,
> 17 generate_multiphase,
> 
> ~/Projects/pymks/pymks/**init**.py in
> 7
> 8 import os
> ----> 9 from .fmks.data.cahn_hilliard import solve as solve_cahn_hilliard
> 10 from .fmks.plot import plot_microstructures
> 11 from .fmks.bases.primitive import PrimitiveTransformer
> 
> ~/Projects/pymks/pymks/fmks/data/cahn_hilliard.py in
> 57 import numpy as np
> 58 from toolz.curried import memoize
> ---> 59 from ..func import curry, map_blocks, ifftn, fftn, iterate_times
> 60
> 61
> 
> ~/Projects/pymks/pymks/fmks/func.py in
> 10 from toolz.curried import iterate, compose, pipe, get, flip
> 11 from toolz.curried import map as fmap
> ---> 12 import deprecated
> 13
> 14
> 
> ModuleNotFoundError: No module named 'deprecated'

I added `Deprecated` as a dependency. See [this](https://github.com/materialsinnovation/pymks/pull/494/files#diff-b7cb75ca59993a879e29bed8cd8469b8R21). You can install it with `pip install Deprecated`.

**Comment by wd15** [comment]
> > ModuleNotFoundError: No module named 'deprecated'
> 
> I added `Deprecated` as a dependency. See [this](https://github.com/materialsinnovation/pymks/pull/494/files#diff-b7cb75ca59993a879e29bed8cd8469b8R21). You can install it with `pip install Deprecated`.

Actually, I'm going to make it so it's not needed unless you're using the old PyMKS. Not a strict dependency.

**Comment by beyucel** [comment]
Yes, I was using the nix-shell from the previous PR. Now I exit and used the new shell  ( with all dependencies)  it does not have any problem!

**Comment by wd15** [comment]
> > > ModuleNotFoundError: No module named 'deprecated'
> > 
> > 
> > I added `Deprecated` as a dependency. See [this](https://github.com/materialsinnovation/pymks/pull/494/files#diff-b7cb75ca59993a879e29bed8cd8469b8R21). You can install it with `pip install Deprecated`.
> 
> Actually, I'm going to make it so it's not needed unless you're using the old PyMKS. Not a strict dependency.

Scrub that. I don't think it's such an issue having it as a dependency.

**Pull request merged**
