### PR TITLE
Issue137 ch initial values

### PR DESCRIPTION
**Pull request by davidbrough1**
Remove lines of code that contain fipy CH simulation.

### CODE REVIEW

**Comment by wd15** [comment]
David, the images seem to be missing from the notebook. Is this on purpose or were they not in there in previous emails?

It might be a good policy to remove all output before committing the notebooks into the repository. What do you think? I'm just worried about the repository becoming huge with all the images that we're accumulating. We have to be cognizant of the size of the images at least. Is there a way to do this with Git/GitHub?

**Comment by wd15** [comment]
I think it makes sense to keep the images in the repository and then later clean it up if we have problems.

See http://stackoverflow.com/questions/2116778/reduce-git-repository-size

**Comment by davidbrough1** [comment]
I did not intentionally leave out the pictures in the notebooks. The purpose of this pull-request was to remove a few lines of code that I was using to call the fipy model that we previously had in PyMKS. 

I was using the fipy model to compare against the current Cahn-Hilliard simulation we have in PyMKS. These lines of code need to be removed from the example.

**Comment by davidbrough1** [comment]
I will resubmit a pull request with the images.

**Comment by davidbrough1** [comment]
The images have now been updated and this is ready to be merged.

**Pull request merged**
