### PR TITLE
 Fiber notebook update

### PR DESCRIPTION
**Pull request by beyucel**
- Fiber notebook updated with fmks functions
 - Plotting are done within the notebooks
 - Documentation is also updated

### CODE REVIEW

**Comment by wd15** [comment]
@beyucel, can you check this one more time? Make sure you're happy with the changes. I can't seem to add you as a review so please just indicate in the comments.

**Comment by beyucel** [comment]
One sentence had an issue and I fixed it. Other than that everything looks good.

**Comment by beyucel** [comment]
Hey, Daniel(@wd15), I looked at your changes and it looks great now. I just saw a typo and fixed it. Then, I made a mistake while I commit the change I made. I think I fixed it and we can merge it now. Please let me know if you have any other comments.

**Comment by wd15** [comment]
Why is there only 1 commit on the branch? I rebased it before I pushed it. Did you also rebase?

**Comment by beyucel** [comment]
I made 2 commits by mistake (and removed the last one) then I rebased it. I probably did something stupid while doing that.

**Comment by wd15** [comment]
I'll try and restore it.

**Comment by wd15** [comment]
My changes disappeared! I'll try and restore them.

**Comment by beyucel** [comment]
I have your changes in my local repo. I will check If your commits are there too!

**Comment by wd15** [comment]
I update the branch again. Since your new changes weren't in a separate commit, there was no way to include them. Remember that you will need to pull from this branch before pushing and you shouldn't need to use force-push.

**Comment by wd15** [comment]
Please add your changes again now.

**Comment by beyucel** [comment]
I will fix this!  I tried to reset my origin (fiberupdate) from the upstream. I did " git reset --hard upstream/fiberupdate " and it caused the same thing (eventhough you said that I don't have to force push) because when I pulled from upstream, it said everything is up to date.
 I will fix this, sorry for this error!!

**Comment by beyucel** [comment]
@wd15, I think I fixed the issue. The change that I made (the last commit) is actually correcting one sentence in one of the markup cells. If you think this doesn't need to be a separate commit, we can squash it to your commit.

**Comment by wd15** [comment]
@beyucel, I'm going to merge this. I prefer to keep different author's commits separate so that they get credit for their changes.

**Comment by beyucel** [comment]
Sounds good

**Pull request merged**
