### PR TITLE
Issue145 docs

### PR DESCRIPTION
**Pull request by wd15**
@ajmedford, @npaulson, @ahmetcecen 

Address #145

# Changes

 - Documentation can now be built on Readthedocs -- http://pymks.readthedocs.io/en/issue145-docs/rst/README.html.
 - Include test coverage and linting.

# Readthedocs

The Makefile no longer uses Pandoc and Jupyter to build the documentation, it uses native Sphinx modules to take care of this now. This works much better on Readthedocs, which can't run a Makefile. The one issue with this is that the include directive does not work for markdown so the markdown file must stand alone (i.e. it can't include stuff from an ipython notebook for example). I mention this because the README.md and intro.ipynb are no longer merged together. I don't think this is a big issue as the expedience of using Readthedocs greatly out weighs this problem. Another benefit of this approach is that the README.md and intro.ipynb works the same on GitHub as it does in the documentation. Thus when Binder is used the initial Binder page is also the intro.ipynb which links all the other notebooks. Basically, the links work the same whether using Readthedocs, rendered on GitHub or with Binder.

# Pylint and Test Coverage

Both Pylint and test-coverage are run with the automated tests now. It will be some work to clean up the code to pass the linter, but worth doing and something that I will address soon. At the moment the TravisCI red cross shows up for the tests in Github, so when merging this will have to be manually checked on Travis CI.

# Other Changes

 - Removed the author's file as this is redundant since GitHub shows the developers.
 - The intro files in `doc/` have been removed -- they are autogenerated so shouldn't be in the repository.

# Notes

  - the travis tests will show a red cross until the code passes linting, which is something I plan to deal with next, but I don't think it should hold up a merge to develop. Should check this manually.
  - The current documentation for the version being merge is as at http://pymks.readthedocs.io/en/issue145-docs/rst/README.html.

# Further work after merge and questions

  - Set Readthedocs settings so up to date with master and make sure the badge in README.md links correctly to the documentation.
  - Should we do a release just so the new docs stuff is on master?
  - When this is merged and released, then we can remove the gh-pages branch altogether and do a redirect.
  - Redirect form pymks.org.

### CODE REVIEW

**Comment by wd15** [comment]
@ajmedford, @npaulson: I can't assign either of you to this pull request.

**Comment by npaulson** [comment]
I'm not very good with git yet, what do I need to do?

Best,
Noah

**Comment by wd15** [comment]
On Fri, Sep 16, 2016 at 1:48 PM, Noah Paulson <notifications@github.com> wrote:
>
> I'm not very good with git yet, what do I need to do?

In some sense it's very easy to merge this pull request, just click
the "Merge Pull Request" button. However, a pull request is basically
an invitation to review the code being submitted. Also you want to
check the following

  - that the tests pass
  - the examples seem to work as they aren't tested in pymks
  - the documentation builds
  - installation works

Travis CI, Readthedocs does most of that for you. Of course, the code
review is largely subjective and is highly dependent on your
familiarity with the code base. If you're not that familiar with Git,
you can do worse than read either https://git-scm.com/book/en/v2 or
browse SWC lesson on git, http://swcarpentry.github.io/git-novice/.

-- 
Daniel Wheeler

**Comment by npaulson** [comment]
Thanks for the extra details Daniel, I'll try and get this going tomorrow.

Best,
Noah

**Comment by wd15** [comment]
@ajmedford, @npaulson, @ahmetcecen, shall I just go ahead and merge this myself? It's not a huge change to the code, just the way the documentation is built.

**Comment by npaulson** [comment]
@wd15 I think that would be good for now. In any case I'm not seeing the "Merge Pull Request" button.

**Comment by wd15** [comment]
'

On Thu, Sep 22, 2016 at 4:34 PM, Noah Paulson <notifications@github.com> wrote:
>
> @wd15 I think that would be good for now. In any case I'm not seeing the "Merge Pull Request" button.

Really? Okay, you weren't a member of the pymks team. I sent you an
invitation. Sign up for the organization and see if you merge the pull
request.




-- 
Daniel Wheeler

**Comment by npaulson** [comment]
I merged the pull request,
is that what I needed to do?

**Comment by wd15** [comment]
On Thu, Sep 22, 2016 at 4:41 PM, Noah Paulson <notifications@github.com> wrote:
>
> I merged the pull request,
> is that what I needed to do?

Yes, thanks so much. There are a few more things to clean up, but I
will deal with that.

-- 
Daniel Wheeler

**Pull request merged**
