### PR TITLE
docs: update stress notebook to use fmks

### PR DESCRIPTION
**Pull request by wd15**

### CODE REVIEW

**Comment by beyucel** [comment]
Travis is failing. Are you still working on this, Daniel?

**Comment by wd15** [comment]
Yes, working on it right now.

**Comment by wd15** [comment]
I removed stress.ipynb from the Circle CI tests as its just hanging. This is an ongoing problem with some notebooks on Circle CI. There was no failure on Circle CI just the hang.

**Comment by wd15** [comment]
@auag92 @beyucel this is ready for your review now

**Comment by wd15** [comment]
@beyucel, do you want to review this now?

**Pull request merged**
